# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iSandbox' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iSandbox
  pod 'SandboxSDK', :path => '../SandboxSDK/'

  target 'iSandboxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iSandboxUITests' do
    # Pods for testing
  end

end
